version: '3.6'
services:
  database:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    container_name: database
    network_mode: "default"
    environment:
        MARIADB_USER: root
        MARIADB_ROOT_PASSWORD: password
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - ./local_db:/var/lib/mysql
    restart: 'always'
    platform: linux/x86_64
